insert into book_store.book_language (language_name, language_code) values ('Khmer', 'km');
insert into book_store.book_language (language_name, language_code) values ('Malagasy', 'mg');
insert into book_store.book_language (language_name, language_code) values ('English', 'en');
insert into book_store.book_language (language_name, language_code) values ('Telugu', 'te');
insert into book_store.book_language (language_name, language_code) values ('Punjabi', 'pa');
insert into book_store.book_language (language_name, language_code) values ('West Frisian', 'fy');

insert into book_store.author (author_first_name, author_last_name) values ('Alistair', 'Jedrzej');
insert into book_store.author (author_first_name, author_last_name) values ('Martica', 'Mulvin');
insert into book_store.author (author_first_name, author_last_name) values ('Bartlet', 'Gamlen');
insert into book_store.author (author_first_name, author_last_name) values ('Linnie', 'Copcote');
insert into book_store.author (author_first_name, author_last_name) values ('Abbie', 'Pringer');
insert into book_store.author (author_first_name, author_last_name) values ('Efrem', 'Binfield');
insert into book_store.author (author_first_name, author_last_name) values ('Adeline', 'Cato');
insert into book_store.author (author_first_name, author_last_name) values ('Ingemar', 'Bartolomeotti');
insert into book_store.author (author_first_name, author_last_name) values ('Johnathon', 'Mingotti');
insert into book_store.author (author_first_name, author_last_name) values ('Willdon', 'Purslow');
insert into book_store.author (author_first_name, author_last_name) values ('Ree', 'Sifflett');
insert into book_store.author (author_first_name, author_last_name) values ('Pauly', 'Rix');
insert into book_store.author (author_first_name, author_last_name) values ('Jamie', 'Sargeaunt');
insert into book_store.author (author_first_name, author_last_name) values ('Jenny', 'Scopham');
insert into book_store.author (author_first_name, author_last_name) values ('Mina', 'Braksper');
insert into book_store.author (author_first_name, author_last_name) values ('Jone', 'Cribbott');
insert into book_store.author (author_first_name, author_last_name) values ('Annadiane', 'Shawcross');
insert into book_store.author (author_first_name, author_last_name) values ('Ronni', 'Sabben');
insert into book_store.author (author_first_name, author_last_name) values ('Anstice', 'Zapatero');
insert into book_store.author (author_first_name, author_last_name) values ('Velma', 'Rigolle');
insert into book_store.author (author_first_name, author_last_name) values ('Iolanthe', 'Shalcros');
insert into book_store.author (author_first_name, author_last_name) values ('Glen', 'Greasley');
insert into book_store.author (author_first_name, author_last_name) values ('Sigismundo', 'Ploughwright');
insert into book_store.author (author_first_name, author_last_name) values ('Cedric', 'Wymer');
insert into book_store.author (author_first_name, author_last_name) values ('Fernando', 'Cornbell');
insert into book_store.author (author_first_name, author_last_name) values ('Brina', 'Ply');
insert into book_store.author (author_first_name, author_last_name) values ('Eda', 'Iron');
insert into book_store.author (author_first_name, author_last_name) values ('Raddie', 'Sibbet');
insert into book_store.author (author_first_name, author_last_name) values ('Janene', 'Gregs');
insert into book_store.author (author_first_name, author_last_name) values ('Wendy', 'Suddell');
insert into book_store.author (author_first_name, author_last_name) values ('Townie', 'Wehner');
insert into book_store.author (author_first_name, author_last_name) values ('Annetta', 'Dulling');
insert into book_store.author (author_first_name, author_last_name) values ('Kelsey', 'Fitzer');
insert into book_store.author (author_first_name, author_last_name) values ('Menard', 'Vango');
insert into book_store.author (author_first_name, author_last_name) values ('Ulises', 'Kezor');
insert into book_store.author (author_first_name, author_last_name) values ('Llywellyn', 'Bohden');
insert into book_store.author (author_first_name, author_last_name) values ('Patricio', 'Glozman');
insert into book_store.author (author_first_name, author_last_name) values ('Shermie', 'Maton');
insert into book_store.author (author_first_name, author_last_name) values ('Sylas', 'Kenaway');
insert into book_store.author (author_first_name, author_last_name) values ('Gualterio', 'Kener');
insert into book_store.author (author_first_name, author_last_name) values ('Uriel', 'Dolling');
insert into book_store.author (author_first_name, author_last_name) values ('Carlin', 'Ovens');
insert into book_store.author (author_first_name, author_last_name) values ('Felizio', 'Bleyman');
insert into book_store.author (author_first_name, author_last_name) values ('Ezri', 'De Paoli');
insert into book_store.author (author_first_name, author_last_name) values ('Domingo', 'Itzhaki');
insert into book_store.author (author_first_name, author_last_name) values ('Cooper', 'Heatlie');
insert into book_store.author (author_first_name, author_last_name) values ('Hewitt', 'Kinnar');
insert into book_store.author (author_first_name, author_last_name) values ('Riva', 'Hitter');
insert into book_store.author (author_first_name, author_last_name) values ('Zorina', 'Cockerham');
insert into book_store.author (author_first_name, author_last_name) values ('Ronnie', 'Hicken');
insert into book_store.author (author_first_name, author_last_name) values ('Archibald', 'Butt Gow');
insert into book_store.author (author_first_name, author_last_name) values ('Evelina', 'Dillingstone');
insert into book_store.author (author_first_name, author_last_name) values ('Berry', 'Englefield');
insert into book_store.author (author_first_name, author_last_name) values ('Norry', 'Mandy');
insert into book_store.author (author_first_name, author_last_name) values ('Eulalie', 'Gianulli');
insert into book_store.author (author_first_name, author_last_name) values ('Binny', 'Jurek');
insert into book_store.author (author_first_name, author_last_name) values ('Phoebe', 'Crosher');
insert into book_store.author (author_first_name, author_last_name) values ('Corliss', 'Culp');
insert into book_store.author (author_first_name, author_last_name) values ('Fawn', 'Serjent');
insert into book_store.author (author_first_name, author_last_name) values ('Towny', 'Leeb');

insert into book_store.publisher (publisher_name) values ('Integrated oil Companies');
insert into book_store.publisher (publisher_name) values ('Services-Misc. Amusement & Recreation');
insert into book_store.publisher (publisher_name) values ('Clothing/Shoe/Accessory Stores');
insert into book_store.publisher (publisher_name) values ('Computer Software: Prepackaged Software');
insert into book_store.publisher (publisher_name) values ('Semiconductors');
insert into book_store.publisher (publisher_name) values ('Telecommunications Equipment');
insert into book_store.publisher (publisher_name) values ('Investment Managers');
insert into book_store.publisher (publisher_name) values ( 'Industrial Machinery/Components');

insert into book_store.order_status (status_value) values ('received');
insert into book_store.order_status (status_value) values ('prepared');
insert into book_store.order_status (status_value) values ('delivered');
insert into book_store.order_status (status_value) values ('cancelled');
insert into book_store.order_status (status_value) values ('payment failed');
insert into book_store.order_status (status_value) values ('payment received');

insert into book_store.country (country_name) values ('China');
insert into book_store.country (country_name) values ('South Korea');
insert into book_store.country (country_name) values ('Philippines');
insert into book_store.country (country_name) values ('Indonesia');
insert into book_store.country (country_name) values ('Serbia');
insert into book_store.country (country_name) values ('China');
insert into book_store.country (country_name) values ('Germany');
insert into book_store.country (country_name) values ('Iran');
insert into book_store.country (country_name) values ('Portugal');
insert into book_store.country (country_name) values ('Sri Lanka');
insert into book_store.country (country_name) values ('Indonesia');
insert into book_store.country (country_name) values ('Russia');
insert into book_store.country (country_name) values ('Thailand');

insert into book_store.address_status (address_status) values ('Mailbox at a building');
insert into book_store.address_status (address_status) values ('Mailbox at a company or firm');
insert into book_store.address_status (address_status) values ('General delivery address');
insert into book_store.address_status (address_status) values ('High-rise default address');
insert into book_store.address_status (address_status) values ('Mailbox at a large volume receiver');
insert into book_store.address_status (address_status) values ('Military address');
insert into book_store.address_status (address_status) values ('Post office box in the address');
insert into book_store.address_status (address_status) values ('Rural route mailbox');
insert into book_store.address_status (address_status) values ('Mailbox at a street address');

insert into book_store.shipping_method (method_name, cost) values ('ground', 22.71);
insert into book_store.shipping_method (method_name, cost) values ('spaceship', 91.46);
insert into book_store.shipping_method (method_name, cost) values ('sea', 20.72);
insert into book_store.shipping_method (method_name, cost) values ('air', 33.27);
insert into book_store.shipping_method (method_name, cost) values ('trebuchet', 6.05);

insert into book_store.book (title, genre, isbn, num_pages, publication_date, language_id, publisher_id) values ('Halfmoon (Paul Bowles - Halbmond)', 'non-fiction', '319824513-3', 915, '12/20/1952', 1, 1);
insert into book_store.book (title, genre, isbn, num_pages, publication_date, language_id, publisher_id) values ('Under the Bombs', 'fiction', '298395214-2', 542, '8/8/1985', 1, 6);
insert into book_store.book (title, genre, isbn, num_pages, publication_date, language_id, publisher_id) values ('Stunt Squad', 'non-fiction', '716337457-7', 931, '10/18/1985', 3, 7);
insert into book_store.book (title, genre, isbn, num_pages, publication_date, language_id, publisher_id) values ('Rush Hour 3', 'fiction', '692504550-6', 226, '4/28/1947', 6, 8);
insert into book_store.book (title, genre, isbn, num_pages, publication_date, language_id, publisher_id) values ('Petting Zoo', 'non-fiction', '324222986-X', 169, '5/30/1998', 2, 4);
insert into book_store.book (title, genre, isbn, num_pages, publication_date, language_id, publisher_id) values ('Bad Fucking', 'non-fiction', '313877999-9', 954, '3/25/2010', 1, 1);
insert into book_store.book (title, genre, isbn, num_pages, publication_date, language_id, publisher_id) values ('Devil''s Carnival, The', 'sci-fi', '040170503-X', 960, '9/13/1921', 4, 4);
insert into book_store.book (title, genre, isbn, num_pages, publication_date, language_id, publisher_id) values ('Redemption: The Stan Tookie Williams Story', 'romance', '906859533-4', 454, '7/5/1958', 4, 4);
insert into book_store.book (title, genre, isbn, num_pages, publication_date, language_id, publisher_id) values ('Moth, The (Cma)', 'sci-fi', '693350006-3', 815, '11/13/2014', 4, 4);
insert into book_store.book (title, genre, isbn, num_pages, publication_date, language_id, publisher_id) values ('Zozo', 'non-fiction', '017740903-7', 837, '5/20/2006', 4, 1);
insert into book_store.book (title, genre, isbn, num_pages, publication_date, language_id, publisher_id) values ('Murk (Mørke)', 'sci-fi', '409830039-7', 554, '4/21/1964', 6, 7);
insert into book_store.book (title, genre, isbn, num_pages, publication_date, language_id, publisher_id) values ('Scribbler, The', 'fiction', '587936460-7', 795, '8/5/1910', 5, 4);
insert into book_store.book (title, genre, isbn, num_pages, publication_date, language_id, publisher_id) values ('I Do', 'sci-fi', '054214185-X', 691, '1/14/1933', 3, 7);
insert into book_store.book (title, genre, isbn, num_pages, publication_date, language_id, publisher_id) values ('Inglorious Bastards (Quel maledetto treno blindato)', 'sci-fi', '713617493-7', 960, '8/19/2018', 4, 1);
insert into book_store.book (title, genre, isbn, num_pages, publication_date, language_id, publisher_id) values ('Thunderball', 'romance', '077903457-0', 783, '6/12/2002', 4, 3);
insert into book_store.book (title, genre, isbn, num_pages, publication_date, language_id, publisher_id) values ('Night at the Museum', 'sci-fi', '763181989-0', 390, '7/8/2009', 6, 3);
insert into book_store.book (title, genre, isbn, num_pages, publication_date, language_id, publisher_id) values ('Crimson Wing: Mystery of the Flamingos, The', 'mystery', '407669453-8', 596, '6/11/1914', 2, 4);
insert into book_store.book (title, genre, isbn, num_pages, publication_date, language_id, publisher_id) values ('Crisis (Kris)', 'romance', '477641832-0', 260, '2/21/1966', 4, 2);
insert into book_store.book (title, genre, isbn, num_pages, publication_date, language_id, publisher_id) values ('Tokyo Trial (Tokyo saiban)', 'romance', '750378678-7', 955, '9/22/1980', 5, 1);
insert into book_store.book (title, genre, isbn, num_pages, publication_date, language_id, publisher_id) values ('Fred & Vinnie', 'romance', '580218698-4', 641, '8/27/1939', 2, 6);
insert into book_store.book (title, genre, isbn, num_pages, publication_date, language_id, publisher_id) values ('Running Out of Time (Am zin)', 'fiction', '793869888-1', 267, '4/26/1937', 1, 5);
insert into book_store.book (title, genre, isbn, num_pages, publication_date, language_id, publisher_id) values ('As Far As My Feet Will Carry Me (So weit die Füße tragen)', 'fiction', '260853479-1', 32, '10/22/1934', 1, 1);
insert into book_store.book (title, genre, isbn, num_pages, publication_date, language_id, publisher_id) values ('Red River', 'romance', '342655258-2', 936, '9/21/2013', 6, 5);
insert into book_store.book (title, genre, isbn, num_pages, publication_date, language_id, publisher_id) values ('Will', 'mystery', '752767765-1', 504, '9/23/1905', 3, 7);
insert into book_store.book (title, genre, isbn, num_pages, publication_date, language_id, publisher_id) values ('Red Riding Hood', 'romance', '042258642-0', 136, '2/20/1941', 5, 4);
insert into book_store.book (title, genre, isbn, num_pages, publication_date, language_id, publisher_id) values ('Full Speed (À toute vitesse)', 'non-fiction', '008714204-X', 39, '10/16/1986', 5, 7);
insert into book_store.book (title, genre, isbn, num_pages, publication_date, language_id, publisher_id) values ('Steve Jobs: The Lost Interview', 'fiction', '146614009-7', 476, '6/4/1989', 4, 2);
insert into book_store.book (title, genre, isbn, num_pages, publication_date, language_id, publisher_id) values ('Green Slime, The', 'fiction', '713646591-5', 819, '3/23/1906', 4, 1);
insert into book_store.book (title, genre, isbn, num_pages, publication_date, language_id, publisher_id) values ('Enemy Mine', 'mystery', '614911631-X', 613, '12/2/1971', 4, 6);
insert into book_store.book (title, genre, isbn, num_pages, publication_date, language_id, publisher_id) values ('Lone Ranger, The', 'fiction', '748162645-6', 541, '8/10/1908', 5, 5);
insert into book_store.book (title, genre, isbn, num_pages, publication_date, language_id, publisher_id) values ('Legend of the Lone Ranger, The', 'fiction', '068467222-7', 95, '5/13/1976', 1, 4);
insert into book_store.book (title, genre, isbn, num_pages, publication_date, language_id, publisher_id) values ('Little Otik (Otesánek)', 'sci-fi', '295777210-8', 139, '11/30/2010', 4, 2);
insert into book_store.book (title, genre, isbn, num_pages, publication_date, language_id, publisher_id) values ('Presentation, or Charlotte and Her Steak (Présentation ou Charlotte et son steak)', 'sci-fi', '468782903-1', 262, '3/1/2016', 2, 2);
insert into book_store.book (title, genre, isbn, num_pages, publication_date, language_id, publisher_id) values ('Hatful of Rain, A', 'sci-fi', '479763003-5', 293, '9/2/1994', 4, 7);
insert into book_store.book (title, genre, isbn, num_pages, publication_date, language_id, publisher_id) values ('Long Night''s Journey Into Day', 'romance', '769265059-4', 91, '6/20/1925', 5, 8);
insert into book_store.book (title, genre, isbn, num_pages, publication_date, language_id, publisher_id) values ('Raise Your Voice', 'non-fiction', '314251953-X', 62, '3/12/1905', 5, 1);
insert into book_store.book (title, genre, isbn, num_pages, publication_date, language_id, publisher_id) values ('Anaconda III', 'sci-fi', '596099139-X', 893, '9/17/1903', 6, 2);
insert into book_store.book (title, genre, isbn, num_pages, publication_date, language_id, publisher_id) values ('Priceless (Hors de prix)', 'mystery', '497199627-3', 614, '1/2/2015', 4, 4);
insert into book_store.book (title, genre, isbn, num_pages, publication_date, language_id, publisher_id) values ('Four Sided Triangle', 'fiction', '339415921-X', 727, '3/10/1906', 2, 7);
insert into book_store.book (title, genre, isbn, num_pages, publication_date, language_id, publisher_id) values ('Johnny English Reborn', 'non-fiction', '944434783-4', 152, '11/28/1920', 6, 3);
insert into book_store.book (title, genre, isbn, num_pages, publication_date, language_id, publisher_id) values ('Glass Key, The', 'mystery', '707433233-X', 989, '8/27/1933', 5, 4);
insert into book_store.book (title, genre, isbn, num_pages, publication_date, language_id, publisher_id) values ('Near Dark', 'non-fiction', '736438756-0', 154, '9/17/2016', 4, 4);
insert into book_store.book (title, genre, isbn, num_pages, publication_date, language_id, publisher_id) values ('10 Rillington Place', 'romance', '784692085-5', 262, '8/30/1972', 2, 2);
insert into book_store.book (title, genre, isbn, num_pages, publication_date, language_id, publisher_id) values ('After Fall, Winter', 'sci-fi', '017772160-X', 200, '5/25/1951', 4, 5);
insert into book_store.book (title, genre, isbn, num_pages, publication_date, language_id, publisher_id) values ('Passion of the Christ, The', 'mystery', '837471411-5', 459, '5/26/1992', 3, 8);
insert into book_store.book (title, genre, isbn, num_pages, publication_date, language_id, publisher_id) values ('Inevitable Defeat of Mister & Pete, The', 'mystery', '583332580-3', 50, '8/27/1908', 3, 4);
insert into book_store.book (title, genre, isbn, num_pages, publication_date, language_id, publisher_id) values ('Innocence', 'fiction', '554766438-3', 626, '3/15/1930', 4, 1);
insert into book_store.book (title, genre, isbn, num_pages, publication_date, language_id, publisher_id) values ('Galaxina', 'fiction', '106656656-9', 900, '8/8/1947', 5, 2);
insert into book_store.book (title, genre, isbn, num_pages, publication_date, language_id, publisher_id) values ('Eye of the Dolphin', 'fiction', '745838402-6', 910, '9/14/1946', 2, 7);
insert into book_store.book (title, genre, isbn, num_pages, publication_date, language_id, publisher_id) values ('Absolute Beginners', 'mystery', '802909593-7', 683, '11/24/1987', 4, 3);
insert into book_store.book (title, genre, isbn, num_pages, publication_date, language_id, publisher_id) values ('No Mercy', 'romance', '006319514-3', 846, '9/17/1906', 2, 2);
insert into book_store.book (title, genre, isbn, num_pages, publication_date, language_id, publisher_id) values ('Caught', 'mystery', '308163418-0', 386, '3/16/1970', 4, 6);
insert into book_store.book (title, genre, isbn, num_pages, publication_date, language_id, publisher_id) values ('Clownhouse', 'romance', '408565755-0', 679, '3/17/1900', 2, 1);
insert into book_store.book (title, genre, isbn, num_pages, publication_date, language_id, publisher_id) values ('Small Roads', 'mystery', '741941163-8', 286, '10/9/2020', 3, 4);
insert into book_store.book (title, genre, isbn, num_pages, publication_date, language_id, publisher_id) values ('Elephants Dream', 'fiction', '769094922-3', 114, '5/9/1955', 2, 7);
insert into book_store.book (title, genre, isbn, num_pages, publication_date, language_id, publisher_id) values ('The Mysterious Island', 'sci-fi', '405654659-2', 896, '2/16/1925', 1, 7);
insert into book_store.book (title, genre, isbn, num_pages, publication_date, language_id, publisher_id) values ('Man Who Sued God, The', 'sci-fi', '388509487-8', 928, '1/27/1976', 3, 4);
insert into book_store.book (title, genre, isbn, num_pages, publication_date, language_id, publisher_id) values ('Beauty and the Beast (Beauty and the Beasts: A Dark Tale)', 'romance', '907653988-X', 204, '10/19/1986', 5, 8);
insert into book_store.book (title, genre, isbn, num_pages, publication_date, language_id, publisher_id) values ('Dead Meat', 'sci-fi', '006306081-7', 969, '7/20/1939', 5, 6);
insert into book_store.book (title, genre, isbn, num_pages, publication_date, language_id, publisher_id) values ('Jönssonligan dyker upp igen', 'mystery', '599749030-0', 551, '10/13/1942', 2, 5);

insert into book_store.book_author (book_id, author_id) values (30, 9);
insert into book_store.book_author (book_id, author_id) values (39, 8);
insert into book_store.book_author (book_id, author_id) values (45, 17);
insert into book_store.book_author (book_id, author_id) values (5, 12);
insert into book_store.book_author (book_id, author_id) values (10, 32);
insert into book_store.book_author (book_id, author_id) values (9, 32);
insert into book_store.book_author (book_id, author_id) values (36, 11);
insert into book_store.book_author (book_id, author_id) values (26, 46);
insert into book_store.book_author (book_id, author_id) values (24, 14);
insert into book_store.book_author (book_id, author_id) values (27, 50);
insert into book_store.book_author (book_id, author_id) values (48, 17);
insert into book_store.book_author (book_id, author_id) values (31, 20);
insert into book_store.book_author (book_id, author_id) values (13, 50);
insert into book_store.book_author (book_id, author_id) values (27, 34);
insert into book_store.book_author (book_id, author_id) values (49, 18);
insert into book_store.book_author (book_id, author_id) values (47, 40);
insert into book_store.book_author (book_id, author_id) values (29, 9);
insert into book_store.book_author (book_id, author_id) values (43, 20);
insert into book_store.book_author (book_id, author_id) values (29, 20);
insert into book_store.book_author (book_id, author_id) values (35, 34);
insert into book_store.book_author (book_id, author_id) values (18, 11);
insert into book_store.book_author (book_id, author_id) values (6, 11);
insert into book_store.book_author (book_id, author_id) values (35, 28);
insert into book_store.book_author (book_id, author_id) values (15, 37);
insert into book_store.book_author (book_id, author_id) values (28, 30);
insert into book_store.book_author (book_id, author_id) values (10, 24);
insert into book_store.book_author (book_id, author_id) values (8, 27);
insert into book_store.book_author (book_id, author_id) values (33, 48);
insert into book_store.book_author (book_id, author_id) values (47, 4);
insert into book_store.book_author (book_id, author_id) values (24, 4);

insert into book_store.customer_phone (phone_number, country_id) values ('952-305-3265', 6);
insert into book_store.customer_phone (phone_number, country_id) values ('535-436-8583', 5);
insert into book_store.customer_phone (phone_number, country_id) values ('295-709-2697', 4);
insert into book_store.customer_phone (phone_number, country_id) values ('166-138-4678', 1);
insert into book_store.customer_phone (phone_number, country_id) values ('755-724-7765', 4);
insert into book_store.customer_phone (phone_number, country_id) values ('878-723-1492', 12);
insert into book_store.customer_phone (phone_number, country_id) values ('440-265-3604', 2);

insert into book_store.customer (first_name, last_name, email, password_hash, password_salt, phone_id) values ('Phedra', 'Montilla', 'pmontilla0@microsoft.com', '$2a$04$jJtk42K17D2PU6iOtiqwI.P89vaEMdWy8vacQHNgaW2ci3r3jYBPO', 'eKeIPYVnmqfQxzj9TonIm8d8e2jNsbGM', null);
insert into book_store.customer (first_name, last_name, email, password_hash, password_salt, phone_id) values ('Fielding', 'Eydel', 'feydel1@spotify.com', '$2a$04$3TA0Jghhf1EaIUVckI9beOFLLloleaDv67EArLj/im61rgbg8aPta', 'e2oEmu06sPW5Ul52apOoK8wrbiTccEDf', null);
insert into book_store.customer (first_name, last_name, email, password_hash, password_salt, phone_id) values ('Jamie', 'Skalls', 'jskalls2@elegantthemes.com', '$2a$04$zhgTfpk1jTZEOT.poQvT.ub2vWHsbMiUeYbqCYFTeGyXkvUGya.UO', '4j8Tj9cURAxlLLkKYkPbsjDPtxfDoJNy', null);
insert into book_store.customer (first_name, last_name, email, password_hash, password_salt, phone_id) values ('Fania', 'McArthur', 'fmcarthur3@mozilla.com', '$2a$04$I3Qpn5O1Oog4DjMLuu7J5.JIhTS9w98GMldMUiIuXMHdl95ORgBlm', 'vnu4ByPP5Ge12MiEgYt7q55u8OpxHMQy', null);
insert into book_store.customer (first_name, last_name, email, password_hash, password_salt, phone_id) values ('Mariejeanne', 'Flescher', 'mflescher4@nba.com', '$2a$04$3Kg3HC8TS99ZKilvXj5XV.3oQtk3Eg4XQ2RpYDTxvuUiYYAdjGPTu', 'oxvQD03LkAVwH2Pj9QEoT2FM9YEaAt2y', null);
insert into book_store.customer (first_name, last_name, email, password_hash, password_salt, phone_id) values ('Skelly', 'Osipenko', 'sosipenko5@mozilla.com', '$2a$04$XgadyXOrRXwdmrqZu6iBEu5sxHaexw4GUIPySyh5Nh8oV47cB04Ga', 'KpzgroNpzb9e4uwojT7cKzFehVSHC6g5', 7);
insert into book_store.customer (first_name, last_name, email, password_hash, password_salt, phone_id) values ('Delbert', 'Boleyn', 'dboleyn6@topsy.com', '$2a$04$eI.jeNCtbSO0fK1/2p37fufUwMnSxEVxuRwWoVFqIX4XqnZGNP/9y', '8ZfkA1Hgjg39rH0VqVTVxNYOfVe4VijO', null);
insert into book_store.customer (first_name, last_name, email, password_hash, password_salt, phone_id) values ('Mandel', 'Escala', 'mescala7@who.int', '$2a$04$sb0O10hLEl11wfKgn3A4zOtcLDRS.5A3ZFMUISk/Ohn2Qwb9xKOV6', 'alAwEKbEQLiyr7Q8ILYD1RFwrFpQCJck', null);
insert into book_store.customer (first_name, last_name, email, password_hash, password_salt, phone_id) values ('Bartie', 'Whitmore', 'bwhitmore8@google.com', '$2a$04$1Ro1GYq1VwvV0Gwbz9Deju5Sb.fqwkQrRFEG8XU5Nm.v5TtSbIiCe', '0fZQV6F4l42xe5c9W6QbmMR8w3gipqd7', null);
insert into book_store.customer (first_name, last_name, email, password_hash, password_salt, phone_id) values ('Eamon', 'Daubney', 'edaubney9@guardian.co.uk', '$2a$04$EHctuLMYc0.r8QuNMb8fcOxuWoT/9dqXrsj2RgemhS0G0qeRkFrL2', 'DYUZNau88eE4KzdGrSawfWVl6NJHuFF4', null);
insert into book_store.customer (first_name, last_name, email, password_hash, password_salt, phone_id) values ('Katharine', 'Filpo', 'kfilpoa@washingtonpost.com', '$2a$04$pM.UAAXV3Xpa70/86yrGL.2JinjEXOHkFC/2yve/pv3YjuzC20/8O', 'fFur9lY8QbSJTP1cWHGWyWpp2g0cTAtc', 4);
insert into book_store.customer (first_name, last_name, email, password_hash, password_salt, phone_id) values ('Dulciana', 'Rumgay', 'drumgayb@shareasale.com', '$2a$04$4VPdhsR.FKS200UwkXCp6u1wmemnyFaT5NUiV0ZzqSGPecuspfJai', 'hdlzoHsfqQf9bM9rLIOPF1oQ1kcXBK0U', null);
insert into book_store.customer (first_name, last_name, email, password_hash, password_salt, phone_id) values ('Michell', 'Helling', 'mhellingc@mit.edu', '$2a$04$pEJqHUZb02jkpQ04mBGuWuSNdjHa3cSxUj6f6A8ec5XH.fSHxnYe.', 'AVEdhsKH5za65fz4sHj6g87QBXj00TMZ', 3);
insert into book_store.customer (first_name, last_name, email, password_hash, password_salt, phone_id) values ('Giselbert', 'Stangoe', 'gstangoed@github.com', '$2a$04$ERlgLNCIEJbqHzHSDEdGS.ACUou8FFyp1gWIUBRBVC.alw6RuP1ie', '5Igvw2nbTZSc2P4nrcVdox8Vq2jqPsVd', null);
insert into book_store.customer (first_name, last_name, email, password_hash, password_salt, phone_id) values ('Mikael', 'Petrichat', 'mpetrichate@narod.ru', '$2a$04$q7tW5gj/trW8cPN3Nox2Je0/DZ45WyFiWi2EEFZ1i0nNDoGtVI1HO', 'VvXzCaRdNPzdFhQZzYDKsJ1JE8GoafPZ', null);

insert into book_store.address (street_number, street_name, city, country_id) values (17, 'Novick', 'Balongmulyo', 9);
insert into book_store.address (street_number, street_name, city, country_id) values (10, 'Michigan', 'Yili', 2);
insert into book_store.address (street_number, street_name, city, country_id) values (16, 'Express', 'Zavitinsk', 7);
insert into book_store.address (street_number, street_name, city, country_id) values (14, 'Packers', 'Kyperoúnta', 8);
insert into book_store.address (street_number, street_name, city, country_id) values (25, 'Forster', 'Carmo do Cajuru', 4);
insert into book_store.address (street_number, street_name, city, country_id) values (13, 'Moland', 'Velestíno', 1);
insert into book_store.address (street_number, street_name, city, country_id) values (59, 'Golf', 'Waco', 10);
insert into book_store.address (street_number, street_name, city, country_id) values (74, 'Monterey', 'Zhongbu', 8);
insert into book_store.address (street_number, street_name, city, country_id) values (28, 'Grover', 'Houzhen', 5);
insert into book_store.address (street_number, street_name, city, country_id) values (59, 'Eliot', 'Beijie', 2);
insert into book_store.address (street_number, street_name, city, country_id) values (59, 'Kropf', 'Ambanja', 10);
insert into book_store.address (street_number, street_name, city, country_id) values (29, 'Fisk', 'Huangnaihai', 6);
insert into book_store.address (street_number, street_name, city, country_id) values (73, 'Moulton', 'Dabbūrīya', 11);
insert into book_store.address (street_number, street_name, city, country_id) values (71, 'Eggendart', 'Corujeira', 1);
insert into book_store.address (street_number, street_name, city, country_id) values (61, 'Bluejay', 'Lianhe', 11);
insert into book_store.address (street_number, street_name, city, country_id) values (9, 'Oneill', 'Picton', 13);
insert into book_store.address (street_number, street_name, city, country_id) values (33, 'Carberry', 'Aliaga', 11);
insert into book_store.address (street_number, street_name, city, country_id) values (41, 'Melody', 'Heyan', 1);
insert into book_store.address (street_number, street_name, city, country_id) values (59, 'Vermont', 'Ajaccio', 9);
insert into book_store.address (street_number, street_name, city, country_id) values (1, 'Cody', 'Waeng Yai', 5);

insert into book_store.customer_order (ordered, is_ready_for_shipping, customer_id, shipping_method_id, destination_address_id) values ('2023-07-04 07:16:19+00', false, 12, 3, 8);
insert into book_store.customer_order (ordered, is_ready_for_shipping, customer_id, shipping_method_id, destination_address_id) values ('2023-01-08 21:18:48+00', true, 13, 3, 3);
insert into book_store.customer_order (ordered, is_ready_for_shipping, customer_id, shipping_method_id, destination_address_id) values ('2023-09-05 02:14:02+00', true, 14, 5, 8);
insert into book_store.customer_order (ordered, is_ready_for_shipping, customer_id, shipping_method_id, destination_address_id) values ('2023-08-25 06:17:04+00', true, 9, 2, 6);
insert into book_store.customer_order (ordered, is_ready_for_shipping, customer_id, shipping_method_id, destination_address_id) values ('2023-06-24 02:44:10+00', false, 2, 1, 12);
insert into book_store.customer_order (ordered, is_ready_for_shipping, customer_id, shipping_method_id, destination_address_id) values ('2023-02-06 13:00:18+00', false, 6, 3, 15);
insert into book_store.customer_order (ordered, is_ready_for_shipping, customer_id, shipping_method_id, destination_address_id) values ('2023-05-15 06:12:27+00', true, 4, 4, 2);
insert into book_store.customer_order (ordered, is_ready_for_shipping, customer_id, shipping_method_id, destination_address_id) values ('2023-04-14 04:02:37+00', true, 2, 5, 6);
insert into book_store.customer_order (ordered, is_ready_for_shipping, customer_id, shipping_method_id, destination_address_id) values ('2023-10-12 22:56:54+00', false, 14, 4, 1);
insert into book_store.customer_order (ordered, is_ready_for_shipping, customer_id, shipping_method_id, destination_address_id) values ('2022-10-18 03:34:21+00', true, 7, 1, 11);
insert into book_store.customer_order (ordered, is_ready_for_shipping, customer_id, shipping_method_id, destination_address_id) values ('2023-09-11 12:15:57+00', true, 5, 2, 3);
insert into book_store.customer_order (ordered, is_ready_for_shipping, customer_id, shipping_method_id, destination_address_id) values ('2022-12-05 16:01:49+00', true, 2, 1, 12);
insert into book_store.customer_order (ordered, is_ready_for_shipping, customer_id, shipping_method_id, destination_address_id) values ('2023-04-25 14:05:52+00', false, 3, 3, 16);
insert into book_store.customer_order (ordered, is_ready_for_shipping, customer_id, shipping_method_id, destination_address_id) values ('2023-01-05 15:22:37+00', true, 7, 1, 8);
insert into book_store.customer_order (ordered, is_ready_for_shipping, customer_id, shipping_method_id, destination_address_id) values ('2022-12-06 00:44:47+00', false, 5, 2, 14);
insert into book_store.customer_order (ordered, is_ready_for_shipping, customer_id, shipping_method_id, destination_address_id) values ('2023-09-11 12:15:57+00', true, 5, 2, 3);
insert into book_store.customer_order (ordered, is_ready_for_shipping, customer_id, shipping_method_id, destination_address_id) values ('2022-12-05 16:01:49+00', true, 2, 1, 12);
insert into book_store.customer_order (ordered, is_ready_for_shipping, customer_id, shipping_method_id, destination_address_id) values ('2023-04-25 14:05:52+00', false, 3, 3, 16);
insert into book_store.customer_order (ordered, is_ready_for_shipping, customer_id, shipping_method_id, destination_address_id) values ('2023-08-25 06:17:04+00', true, 9, 2, 6);
insert into book_store.customer_order (ordered, is_ready_for_shipping, customer_id, shipping_method_id, destination_address_id) values ('2023-06-24 02:44:10+00', false, 2, 1, 12);

insert into book_store.order_line (order_id, book_id, cost) values (14, 44, 97);
insert into book_store.order_line (order_id, book_id, cost) values (6, 44, 257);
insert into book_store.order_line (order_id, book_id, cost) values (1, 5, 264);
insert into book_store.order_line (order_id, book_id, cost) values (18, 50, 4);
insert into book_store.order_line (order_id, book_id, cost) values (9, 48, 373);
insert into book_store.order_line (order_id, book_id, cost) values (16, 4, 300);
insert into book_store.order_line (order_id, book_id, cost) values (10, 42, 68);
insert into book_store.order_line (order_id, book_id, cost) values (9, 21, 126);
insert into book_store.order_line (order_id, book_id, cost) values (20, 35, 212);
insert into book_store.order_line (order_id, book_id, cost) values (14, 5, 284);

insert into book_store.order_history (order_id, status_id, status_date) values (11, 6, '2/3/2023');
insert into book_store.order_history (order_id, status_id, status_date) values (5, 6, '9/21/2023');
insert into book_store.order_history (order_id, status_id, status_date) values (11, 5, '5/27/2023');
insert into book_store.order_history (order_id, status_id, status_date) values (16, 4, '9/18/2023');
insert into book_store.order_history (order_id, status_id, status_date) values (4, 1, '7/25/2023');
insert into book_store.order_history (order_id, status_id, status_date) values (10, 5, '5/21/2023');
insert into book_store.order_history (order_id, status_id, status_date) values (4, 5, '5/6/2023');
insert into book_store.order_history (order_id, status_id, status_date) values (15, 2, '8/16/2023');
insert into book_store.order_history (order_id, status_id, status_date) values (13, 4, '10/25/2022');
insert into book_store.order_history (order_id, status_id, status_date) values (4, 6, '6/22/2023');

insert into book_store.customer_address (customer_id, address_id, status_id) values (1, 11, 2);
insert into book_store.customer_address (customer_id, address_id, status_id) values (8, 9, 3);
insert into book_store.customer_address (customer_id, address_id, status_id) values (9, 17, 4);
insert into book_store.customer_address (customer_id, address_id, status_id) values (3, 5, 3);
insert into book_store.customer_address (customer_id, address_id, status_id) values (14, 15, 2);
insert into book_store.customer_address (customer_id, address_id, status_id) values (9, 15, 4);
insert into book_store.customer_address (customer_id, address_id, status_id) values (15, 11, 5);
insert into book_store.customer_address (customer_id, address_id, status_id) values (10, 16, 4);
insert into book_store.customer_address (customer_id, address_id, status_id) values (8, 6, 4);
insert into book_store.customer_address (customer_id, address_id, status_id) values (14, 10, 3);

-- bds-project-assignment-3

UPDATE "book_store"."customer"
   SET "password_salt" = '+Nm++gOYzX3CyL5zuqWZmA==',
       "password_hash" = 'JDJhJDEyJDhMazg4ZU1XeFYxQXdKM3hzb1VYay5jUkF1dUsvSi43N3RVcm8wamxSUVdtMnRibDhCMFpD';